const globals = {
  AONC: 'readonly',
  browser: 'readonly',
  chrome: 'readonly',
  window: 'writable',
  document: 'writable',
  localStorage: 'writable',
  sessionStorage: 'writable',
  navigator: 'readonly',
  location: 'writable',
  history: 'writable',
  getComputedStyle: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  MutationObserver: 'readonly',
  NodeFilter: 'readonly',
  URL: 'readonly',
  Blob: 'readonly',
  FileReader: 'readonly',
  Image: 'readonly',
  CSS: 'readonly',
  fetch: 'readonly',
  Response: 'readonly',
  Promise: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  console: 'readonly',
  globalThis: 'writable',
  self: 'readonly',
  importScripts: 'readonly',
  WeakSet: 'readonly',
  Map: 'readonly',
  Set: 'readonly',
  JSON: 'readonly',
  Math: 'readonly',
  Date: 'readonly',
  Object: 'readonly',
  Array: 'readonly',
  String: 'readonly',
  Number: 'readonly',
  Boolean: 'readonly',
  RegExp: 'readonly',
  Error: 'readonly',
  TypeError: 'readonly',
  isNaN: 'readonly',
  isFinite: 'readonly',
  parseInt: 'readonly',
  parseFloat: 'readonly',
  encodeURIComponent: 'readonly',
  decodeURIComponent: 'readonly',
  matchMedia: 'readonly',
  parent: 'readonly',
  top: 'readonly',
  postMessage: 'readonly',
  addEventListener: 'readonly',
  removeEventListener: 'readonly',
  devicePixelRatio: 'readonly',
  innerWidth: 'readonly',
  innerHeight: 'readonly',
  scrollY: 'readonly',
  pageYOffset: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  open: 'readonly',
  DOMParser: 'readonly',
  AbortController: 'readonly',
  URLSearchParams: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  HTMLElement: 'readonly',
  Node: 'readonly'
};

export default [
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', varsIgnorePattern: '^_', caughtErrors: 'none' }],
      'no-dupe-keys': 'error',
      'no-dupe-args': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'error',
      'no-self-assign': 'error',
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-fallthrough': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-invalid-regexp': 'error',
      'no-regex-spaces': 'error',
      'no-sparse-arrays': 'error',
      'no-unsafe-negation': 'error',
      'valid-typeof': 'error',
      'no-func-assign': 'error',
      'no-obj-calls': 'error',
      'no-compare-neg-zero': 'error',
      'no-ex-assign': 'error',
      'no-import-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'use-isnan': 'error'
    }
  },
  {
    files: ['tools/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        require: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        URL: 'readonly',
        JSON: 'readonly',
        Math: 'readonly',
        Object: 'readonly',
        Array: 'readonly',
        String: 'readonly',
        Number: 'readonly',
        Boolean: 'readonly',
        RegExp: 'readonly',
        Error: 'readonly',
        Map: 'readonly',
        Set: 'readonly',
        Promise: 'readonly',
        encodeURIComponent: 'readonly',
        fetch: 'readonly'
      }
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
      'no-dupe-keys': 'error',
      'no-unreachable': 'error',
      'no-fallthrough': 'error'
    }
  }
];
