AONC.define('content.picker.panelCssText', function () {
  'use strict';

  return [
    '.panel{position:fixed;top:16px;right:16px;width:340px;max-height:calc(100vh - 32px);',
    'overflow:auto;pointer-events:auto;background:var(--bg);border:1px solid var(--line);',
    'border-radius:14px;box-shadow:0 24px 60px rgba(0,0,0,.6);display:flex;flex-direction:column;}',
    '.hd{display:flex;align-items:center;gap:8px;padding:11px 13px;border-bottom:1px solid var(--line);',
    'position:sticky;top:0;background:var(--bg);z-index:2;}',
    '.hd b{font-size:13px;font-weight:700;letter-spacing:.2px;}',
    '.sp{flex:1;}',
    '.ic{width:26px;height:26px;border-radius:7px;border:1px solid var(--line);background:var(--bg2);',
    'color:var(--fg);cursor:pointer;display:grid;place-items:center;font-size:13px;line-height:1;padding:0;}',
    '.ic:hover{background:var(--bg3);border-color:var(--accent);}',
    '.ic.danger:hover{border-color:#ff5c5c;color:#ff8080;}',
    '.bd{padding:12px 13px;display:flex;flex-direction:column;gap:12px;}',
    '.crumb{font-size:11px;color:var(--dim);font-family:ui-monospace,Menlo,monospace;',
    'word-break:break-all;line-height:1.5;}',
    '.sel{display:flex;gap:6px;align-items:flex-start;}',
    '.sel textarea{flex:1;min-height:52px;resize:vertical;background:#101014;color:#c9f2c9;',
    'border:1px solid var(--line);border-radius:8px;padding:7px 8px;',
    'font-family:ui-monospace,Menlo,monospace;font-size:11px;line-height:1.5;}',
    '.sel textarea:focus{outline:none;border-color:var(--accent);}',
    '.row{display:flex;align-items:center;gap:8px;}',
    '.row label{flex:1;font-size:12px;color:var(--dim);}',
    '.row output{font-size:11px;color:var(--fg);min-width:44px;text-align:right;',
    'font-family:ui-monospace,Menlo,monospace;}',
    'input[type=range]{flex:1.4;height:4px;-webkit-appearance:none;appearance:none;background:var(--bg3);',
    'border-radius:99px;outline:none;}',
    'input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;width:14px;height:14px;border-radius:50%;',
    'background:var(--accent);cursor:pointer;border:2px solid #0e0e12;}',
    'input[type=range]::-moz-range-thumb{width:12px;height:12px;border-radius:50%;background:var(--accent);',
    'cursor:pointer;border:2px solid #0e0e12;}',
    'input[type=color]{width:32px;height:26px;padding:0;border:1px solid var(--line);border-radius:7px;',
    'background:var(--bg2);cursor:pointer;}',
    'input[type=text]{flex:1;background:#101014;border:1px solid var(--line);border-radius:8px;',
    'padding:6px 8px;color:var(--fg);font-size:12px;}',
    'input[type=text]:focus{outline:none;border-color:var(--accent);}',
    'select{flex:1;background:#101014;border:1px solid var(--line);border-radius:8px;padding:6px 8px;',
    'color:var(--fg);font-size:12px;}',
    '.tabs{display:flex;gap:4px;background:var(--bg2);padding:3px;border-radius:9px;}',
    '.tabs button{flex:1;border:0;background:transparent;color:var(--dim);font-size:12px;',
    'padding:6px 4px;border-radius:7px;cursor:pointer;font-weight:600;}',
    '.tabs button.on{background:var(--accent);color:#fff;}',
    '.sec{display:flex;flex-direction:column;gap:9px;}',
    '.sec[hidden]{display:none;}',
    '.ttl{font-size:10px;text-transform:uppercase;letter-spacing:.09em;color:var(--dim);font-weight:700;}',
    '.btn{border:1px solid var(--line);background:var(--bg2);color:var(--fg);border-radius:9px;',
    'padding:8px 10px;font-size:12px;font-weight:600;cursor:pointer;}',
    '.btn:hover{border-color:var(--accent);background:var(--bg3);}',
    '.btn.primary{background:var(--accent);border-color:var(--accent);color:#fff;}',
    '.btn.primary:hover{filter:brightness(1.1);}',
    '.btn.wide{width:100%;}',
    '.btns{display:grid;grid-template-columns:1fr 1fr;gap:6px;}',
    '.num{flex:0 0 auto;width:72px;background:#101014;border:1px solid var(--line);border-radius:8px;',
    'padding:5px 6px;color:var(--fg);font-size:11px;text-align:right;',
    'font-family:ui-monospace,Menlo,monospace;}',
    '.num:focus{outline:none;border-color:var(--accent);}',
    '.grid2{display:grid;grid-template-columns:1fr 1fr;gap:6px;}',
    '.sw{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--fg);cursor:pointer;}',
    '.sw input{accent-color:var(--accent);width:15px;height:15px;}',
    '.ft{padding:10px 13px;border-top:1px solid var(--line);display:flex;gap:6px;',
    'position:sticky;bottom:0;background:var(--bg);}',
    '.hint{font-size:11px;color:var(--dim);line-height:1.5;}',
    '.kbd{display:inline-block;background:var(--bg3);border:1px solid var(--line);border-radius:4px;',
    'padding:0 4px;font-size:10px;font-family:ui-monospace,Menlo,monospace;}',
    '.badge{font-size:10px;background:var(--bg3);border:1px solid var(--line);border-radius:99px;',
    'padding:1px 7px;color:var(--dim);}'
  ].join('\n');
});
